# https://ops.tips/blog/travis-ci-push-docker-image/

language: go

go:
  - "1.11.x"
  - master

sudo: required

services:
  - docker

before_install:
  - sudo apt update -y
  - sudo apt install golang-go -y

script:
  - go test .
  - docker build -t terorie/od-database-crawler

after_success:
  - if [[ "$TRAVIS_BRANCH" == "stable" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker push terorie/od-database-crawler ;
    fi
